name       : python-typogrify
version    : 2.0.7
release    : 1
source     :
    - https://files.pythonhosted.org/packages/8a/bf/64959d6187d42472acb846bcf462347c9124952c05bd57e5769d5f28f9a6/typogrify-2.0.7.tar.gz : 8be4668cda434163ce229d87ca273a11922cb1614cb359970b7dc96eed13cb38
license    : BSD-3-Clause
component  : programming.python
summary    : Typogrify provides a set of custom filters that automatically apply various transformations to plain text in order to yield typographically-improved HTML
description: |
    Typogrify provides a set of custom filters that automatically apply various transformations to plain text in order to yield typographically-improved HTML.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
